baseURL = "https://quang-h-tran.github.io/"
languageCode = "en-us"
theme = "raditian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Research"
  URL = "#portfolio"
  weight = 3

  [[menu.header]]
  name = "CV"
  URL = "#CV"
  weight = 4

  [[menu.header]]
  name = "Contact"
  URL = "mailto:quangtran@utexas.edu"
  weight = 5


  [[menu.footer]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Research"
  URL = "#portfolio"
  weight = 3

  [[menu.footer]]
  name = "CV"
  URL = "#CV"
  weight = 4

  [[menu.footer]]
  name = "Contact"
  URL = "mailto:quangtran@utexas.edu"
  weight = 5


[params]

  #sections = ["showcase", "about", "client-and-work", "education", "experience", "testimonial", "contact"]
  sections = ["showcase", "about", "client-and-work", "education", "testimonial", "experience"]

  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Quang H. Tran"
    text2 = "Graduate Student"

  [params.footer]
      copyright = "Design by © Raditian. All rights reserved."
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"
